name: Kyba

description: Kyba company

url:

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM

sass:
  style: :compressed

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
