name: Kyba

description: Kyba company

avatar: assets/img/kyba.company.png

email: igordoxnadze@gmail.com

phone: 
  number: +38 (096) 258-39-52
  clean: 0962583952

domain: kyba.company

url: https://kyba.company

baseurl: ""

permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  startings: []

kramdown:
  input: GFM

sass:
  style: :compressed

#plugins
gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
